ALTER TABLE records ADD COLUMN IF NOT EXISTS customer_id BIGINT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS customer_name VARCHAR(100);
ALTER TABLE records ADD COLUMN IF NOT EXISTS customer_phone VARCHAR(30);
ALTER TABLE records ADD COLUMN IF NOT EXISTS customer_remark TEXT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS project_id BIGINT;
ALTER TABLE records ADD COLUMN IF NOT EXISTS project_name VARCHAR(100);
