export default defineAppConfig({
  __usePrivacyCheck__: true,
  pages: [
    "pages/calendar/index",
    "pages/login/index",
    "pages/profile/index",
    "pages/calendar-create/index",
    "pages/calendar-detail/index",
    "pages/calendar-members/index",
    "pages/invite-accept/index",
    "pages/record-create/index",
    "pages/schedule-special/index",
    "pages/customer-history/index",
    "pages/customer/index",
    "pages/customer/edit",
    "pages/customer/select",
    "pages/record-detail/index",
    "pages/record-edit/index",
    "pages/invite/index",
    "pages/home/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#ffffff",
    navigationBarTitleText: "轻记协同",
    navigationBarTextStyle: "black",
  },
});
